name: CI Node.js
on: [push, pull_request]
jobs: 
    build-and-test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout do código
            uses: actions/checkout@v3

          - name: Configurar Noje.js
            uses: actions/setup-node@v3
            with:
              node-version: 18
        
          - name: Instalar dependências
            run: npm install

          - name: Rodar lint
            run: npm run lint

          - name: Rodar testes
            run: npm run test

          - name: Build do projeto
            run: npm run build